"""add_strava_fields_to_users

Revision ID: 6176679a6b2b
Revises: 0f89be1d960c
Create Date: 2026-01-19 20:57:10.813794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6176679a6b2b'
down_revision: Union[str, Sequence[str], None] = '0f89be1d960c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('strava_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('strava_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('strava_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_strava_id'), 'users', ['strava_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_strava_id'), table_name='users')
    op.drop_column('users', 'strava_token_expires_at')
    op.drop_column('users', 'strava_refresh_token')
    op.drop_column('users', 'strava_access_token')
    op.drop_column('users', 'strava_id')
    # ### end Alembic commands ###
